### ISSUE TITLE
How can I replace the default with another robotic arm?

### ISSUE THREAD

**Issue by Arthur151** [stepjam/RLBench#1]
If I want to replace the default arm with another robotic arm in the lab, how can make it?

**Comment by stepjam** [comment]
Hi,

You can edit the V-REP file `rlbench/task_design.ttt` and import the robot that you need. You will then need to modify [this line](https://github.com/stepjam/RLBench/blob/master/rlbench/environment.py#L81). This relies on the fact that the robot is already in PyRep. I plan to include better documentation for this. Expect this in about a weeks time :)

Keep in mind a few things:
- The tasks have only been tested on the panda.
- Any sim-only benchmarking should be done on the panda.

**Comment by cy5e** [comment]
Following this question, how can we add multiple arms into rlbench environment?
