### ISSUE TITLE
Multiple arms support? 

### ISSUE THREAD

**Issue by cy5e** [stepjam/RLBench#10]
Hi Stephen, 

Thanks for open sourcing your work! Is there a way to add more arms into the environment and design tasks that use multiple arms? 

Thanks!

**Comment by stepjam** [comment]
Hi,
Sorry for the delay in getting back to you (I've been away).

Multi arm support would be very nice! It shouldn't be too difficult to add in using a fork, but unfortunately I am far too swamped to add this in at the moment. If you want to give a stab at this, you will need to change how scene.py/task.py does the waypoint grabbing for the demos. At the moment, they look for dummies named 'waypoint0', 'waypoint1', etc. You might want to change this to 'arm0_waypoint0', 'arm1_waypoint0', etc. You will also need to add the arms (which hopefully are already implemented in PyRep) to the scene file (.ttt).

Best,
Stephen
