### ISSUE TITLE
Adding Two UR5 and Create Task

### ISSUE THREAD

**Issue by kamaleshrathinam** [stepjam/RLBench#100]
Hi,
Can you tell me how can I add two UR5 robots to the scene and create a complex task so that I can generate data

**Comment by haijunsu-osu** [comment]
we need UR5 model also.

**Comment by stepjam** [comment]
Hi. What gripper would you like attached?

**Comment by kamaleshrathinam** [comment]
Robotiq 85

**Comment by haijunsu-osu** [comment]
robotiq hand-E gripper.

sent by Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by haijunsu-osu** [comment]
Hi,

When do we expect that the support of hand-E gripper and UR5 are implemented in RLBench?

**Comment by stepjam** [comment]
I'll find some time to add the UR5 & 3 today.
Having **two** arms in the scene simultaneously is not something I plan to support, and is out of scope of RLBench. I recommend directly using PyRep instead for dual-arm tasks.

**Comment by stepjam** [comment]
UR5 is now in version (branch) 1.1.0. See the examples/swap_arm.py to see how to swap the arm.
Please note that alternative arms have **limited** support; they may not work with all tasks, as all of the tasks have been designed to be completed with the Panda.
