### ISSUE TITLE
Training time for RLBench gym environments

### ISSUE THREAD

**Issue by Jason-CKY** [stepjam/RLBench#106]
Hi, I am trying to train a Hierarchical Reinforcement Learning (HRL) agent to solve the tasks (1) open-box, (2) block-pyramid and (3) place_shape_in_shape_sorter using just the wrist-rgb camera view.

I am using option-critic algorithm to learn, and the problem with the environments is the sparse rewards. With environment like the block pyramid and shape sorter, I don't think it is feasible to ever encounter the reward through random exploration, thus never giving a learning signal to the agent.

How long does it take an average for an agent to learn these tasks? I have set the training to be 2e7 timesteps, and it is taking an absurdly long time to complete training (~3000 hours). 

Below are my episode return curves for the environments. The agent seems to be able to get the positive reward often enough through random exploration for the open-box environment, but totally seem to be stuck with 0 returns for the block-pyramid and shape sorter environment.

Open-box:
![image](https://user-images.githubusercontent.com/27609953/106363467-aff65280-6363-11eb-800b-352434830146.png)

Block-pyramid:
![image](https://user-images.githubusercontent.com/27609953/106363522-05cafa80-6364-11eb-8215-a4ade986ac89.png)

Place_Shape_in_shape_sorter:
![image](https://user-images.githubusercontent.com/27609953/106363524-082d5480-6364-11eb-98fb-14848e8a267e.png)

What methods do most people use to successfully learn these environments?

**Comment by stepjam** [comment]
Hi, thanks for your question.

RLBench can be seen as a sort of grand challenge for robotics. The idea is that in the real world we don't have shaped rewards, and must find algorithms that can learn with sparse rewards; potentially by making use of demonstrations instead. The paper outlines this best: https://arxiv.org/abs/1909.12271
You can't expect to take a method off the shelf and expect it to work well on RLBench, this is not what the benchmark was intended to do. 

So to answer your question:
`What methods do most people use to successfully learn these environments?`
The short answer is that there currently doesn't exist an exploration-only based RL method that can work on all tasks.

All the best,
Stephen
