### ISSUE TITLE
Missing step in task creation tutorial.

### ISSUE THREAD

**Issue by danfeiX** [stepjam/RLBench#11]
I might be missing something, but it looks like an important step in creating the task in https://github.com/stepjam/RLBench/blob/master/tutorials/simple_task.md is to make the box not collidable. Otherwise the path will be planned around the box as opposed to through it.

**Comment by stepjam** [comment]
Hi,
Sorry for the delay in getting back to you (I've been away).
Thanks for pointing out! Will fix this soon!
Best,
Stephen

**Comment by takuma-ynd** [comment]
I thought the missing step is to add `ignore_collision()` in _waypoint1_, and I created a pull request #80

**Comment by stepjam** [comment]
Thanks. Merged into master.
