### ISSUE TITLE
Running one of the examples in headless mode

### ISSUE THREAD

**Issue by Bowen-He** [stepjam/RLBench#112]
Hi, I'm just trying to use one of the examples to make sure that I install all the components correctly.
The command I was using is
`xvfb-run python3 few_shot_rl.py`.
And in the python file I adjusted the env variable into
`Environment(action_mode, obs_config=obs_config, headless=True)`.
However, I still get an error going as the attachment file.
![捕获](https://user-images.githubusercontent.com/71317990/110201763-cd0ccc80-7e9f-11eb-9449-b91d00702f77.PNG)
I'm sure that I installed PyRep correctly, since I could use the same command to run one of examples there.
Could you please help me firgure where the problem is and how to fix it?

**Comment by stepjam** [comment]
Hi,
When running headless, could you try running Xvfb like this instead:
```
Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset &
export DISPLAY=:99
python3 few_shot_rl.py
```

Also, I assume you do not get this error when **not** running headless?

**Comment by stepjam** [comment]
@Bowen-He Did this resolve your issue?

**Comment by Bowen-He** [comment]
@stepjam Yes, kind of. Now I can use the environment by using Gym. But still got the problem with other modes. I think there might be some conflicts with my system, I'll check it out and try to correct them. Thanks for your help! And I think we can close the issue now!

**Comment by stepjam** [comment]
Feel free to reopen if you have any other queries

**Comment by stepjam** [comment]
You can now do GPU rendering: https://github.com/stepjam/RLBench/blob/master/README.md#running-headless
