### ISSUE TITLE
Customizing the reward as dense function

### ISSUE THREAD

**Issue by mch5048** [stepjam/RLBench#115]
I first appreciate the contributors for maintaining this awesome and handy API. It really helps to accelerate my research on robot learning.

I am working on the customized RL environment that generates the dense reward signal (e.g. reward proportional to negative euclidean distance between the end-effector and the  target object).

I somehow can modify the low-level modules like `step()` method in `task_environment,py `to generate a dense reward signal.  
However, I find it a little hacky in that I should modify the module that is shared by multiple environments.

AFAIK, RLBench is designed to learn the sparse reward tasks, so I assume the manual modification of low-level modules is inevitable for my case. 

If not, I would be grateful for the help regarding this issue.

Thanks in advance!

**Comment by stepjam** [comment]
Hi,
RLBench does actually support the addition of user specified rewards. All you have to do is override the [`reward()`](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/task.py#L115) function in the desired task. I.e. Adding a reward() function to reach_target.py.

**Comment by mch5048** [comment]
@stepjam Oh, why haven't I thought about that! Thank you for the quick response!!!

**Comment by hahans** [comment]
@mch5048 
Did you succeed? I added the reward function in open_drawer.py but the reward in code: 'obs, reward, terminate = task.step(action)' is always 0
