### ISSUE TITLE
Best practice for overriding observation config.

### ISSUE THREAD

**Issue by mch5048** [stepjam/RLBench#117]
Hi, I'm working on a custom task that generates RGBD observation and state vector different from the default
vision and low-level state defined in the RLBench.

For example, I want to generate RGB observation with OPENGL3 renderer with a size of 64*64. Thus, I am trying
to implement my own setting of the ObservationConfig() in RLBench.

If I am to acquire such information for each step and reset of the environment, what can be the best practice to define
such custom configuration not altering the default setup?

Thanks in advance!

**Comment by stepjam** [comment]
The ObservationConfig is meant to customise the observations. So if you want the OPENGL3 renderer with res 64x64, you can do:

```python
cam_config= CameraConfig(image_size=(64, 64), render_mode=RenderMode.OPENGL3)
obs_config = ObservationConfig(left_shoulder_camera=cam_config, front_camera=cam_config)
```

And then pass this to the env:

```python
action_mode = ActionMode(ArmActionMode.ABS_JOINT_VELOCITY)
env = Environment(action_mode, obs_config=obs_config)
```

**Comment by mch5048** [comment]
Thank you for the prompt response! I'm impressed by the systematic design every time I use it.
