### ISSUE TITLE
[Task builder] Adding static objects under the task dummy hierarchy

### ISSUE THREAD

**Issue by mch5048** [stepjam/RLBench#118]
Hi, I'm working on the custom environment where there are respondable (collidiable, but static) walls around the table
of default RLBench table.

AFAIK, RLBench tries to spawn the task dummy inside the workspace with some rotation for each episode.
What could be the best practice if I don't want the walls to be spawned with the random rotation for each episode?

Thanks in advance!

**Comment by stepjam** [comment]
Hi.
You can simply override [is_static_workspace](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/task.py#L159) in your task file, and return True.

**Comment by mch5048** [comment]
Thank you for your help!
