### ISSUE TITLE
Raise error "QObject::~QObject: Timers cannot be stopped from another thread"

### ISSUE THREAD

**Issue by pigranya1218** [stepjam/RLBench#12]
I look this good framework for study.
When run single_task_rl.py with stackBlocks task it is stopped and raised this error.

![image](https://user-images.githubusercontent.com/37202668/67453245-11a81700-f661-11e9-8263-0a8cef049136.png)

How can I fix this?

**Comment by stepjam** [comment]
Hi,
Sorry for the delay in getting back to you (I've been away).
Yes this is a know problem with PyRep, but this is not something that you need to worry about; it does not crash your program, but always prints out when the simulation is shutdown.
Best,
Stephen
