### ISSUE TITLE
How to get camera intrinsics?

### ISSUE THREAD

**Issue by ericrosenbrown** [stepjam/RLBench#122]
How do I get the intrinsic matrix of the cameras for RLBench? Thanks!

**Comment by ericrosenbrown** [comment]
I found the answer in PyRep VisionSensor Object: https://github.com/stepjam/PyRep/blob/master/pyrep/objects/vision_sensor.py

**Comment by stepjam** [comment]
Hi.
There will be an update to version 1.1.0 which allows this in a nice way. For now, you can simply do:
```python
left_cam_intr = my_task_env._scene._cam_over_shoulder_left.get_intrinsic_matrix()
right_cam_intr = my_task_env._scene._cam_over_shoulder_right.get_intrinsic_matrix()
...
```

**Comment by ericrosenbrown** [comment]
thanks for the quick reply! I tried running this, and got the error:

AttributeError: 'VisionSensor' object has no attribute 'get_intrinsic_matrix'

It looks like _cam_over_shoulder_left is a VisionSensor object from PyRep, and it doesn't look like there is a get_intrinsic_matrix() function in the class?  https://github.com/stepjam/PyRep/blob/master/pyrep/objects/vision_sensor.py

**Comment by stepjam** [comment]
You will need to swap to the 'dev' branch for PyRep; https://github.com/stepjam/PyRep/blob/dev/pyrep/objects/vision_sensor.py#L168

**Comment by ericrosenbrown** [comment]
Thank you so much, this is exactly what I needed!
