### ISSUE TITLE
Gripper action should not run in loop

### ISSUE THREAD

**Issue by robfiras** [stepjam/RLBench#127]
I think that it is misleading that the gripper action is running in a loop. From the perspective of the agent/learner, this leads to different effective step-sizes of the simulation depending on whether the gripper is used or not. 

My agents utilize the gripper action to have a greater step-size during reaching in any of the tasks; i.e., the are constantly closing and opening the gripper while approaching an object.

**Comment by stepjam** [comment]
I believe this has been resolved in newer versions :)
