### ISSUE TITLE
What are gripper touch forces in observation?

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#13]
I'm printing out the gripper touch forces on the observation state and I see it is a vector of 6 floats. Am I to interpret that as the 3-D contact force felt by each of the two fingers (e.g. first 3 values are force for one finger and the last 3 are forces for the other finger)? Or is it a 6-D wrench with 3 force values and 3 torque values?

**Comment by stepjam** [comment]
Hi,
Sorry for the delay in getting back to you (I've been away).

The observation gives you the former: the applied forces along the sensor's x, y and z-axes for each of the grippers.

Best,
Stephen
