### ISSUE TITLE
'QWidget: Must construct a QApplication before a QWidget'

### ISSUE THREAD

**Issue by Alpermeric** [stepjam/RLBench#130]
Hi,

First of all, thank you for opening your beautiful project to everyone. When I want to try out the sample scenarios in the examples folder: 'QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped) 'error and it doesn't work. I'm running 'python single_task_rlbench.py' with this command. Have you had an error like this before? If so, do you know the solution?

Thanks.
Alper

**Comment by stepjam** [comment]
Thank you!
Sorry for delay. I’ll assume that this is no longer an issue. Please feel free to reopen a new issue if it is still a problem.
