### ISSUE TITLE
Panda URDF and world to robot coordinate frame transformation matrix 

### ISSUE THREAD

**Issue by StephAO** [stepjam/RLBench#134]
Hi,

Thank you for spending the time to develop such an extensive framework. 

I have been running into a few issues as I have wanted to use my own inverse kinematics solver to have more control. However, I am running into a few in this regard and was hoping you could help on either front:

1. Could your provide the original URDFs used to import the robots to CoppeliaSim? I am using the Panda, and while I can find other URDFs online, however they seem to differ slightly (e.g. the other URDFs have a "panda_hand" link which the one in CoppeliaSim does not seem to have).
2. Could you provide a transformation matrix that maps the global coordinate frame and the robots intrinsic coordinate frame?

Thank you in advance,

Stephane

**Comment by stepjam** [comment]
Hi! This is actually more of a CoppeliaSim question than a RLBench one. I’d recommend asking your question here: https://forum.coppeliarobotics.com/

**Comment by eugeneteoh** [comment]
FYI I raised a PR to add the panda urdf
https://github.com/stepjam/RLBench/pull/201
