### ISSUE TITLE
[Announcement] CoppeliaSim Version Expired

### ISSUE THREAD

**Issue by stepjam** [stepjam/RLBench#141]
Just an announcement that I am aware Version 4.1 of CoppeliaSim has expired. This should be resolved within the next few days. After the fix, you will need to update PyRep/CoppeliaSim: https://github.com/stepjam/PyRep#install 

In the meantime, see here for a quick fix:
https://github.com/stepjam/PyRep/issues/285#issuecomment-881340474

**Comment by deepdad** [comment]
How are you able to get performance? Our experiments run very slow. It seems that it is the CSim part that is slow: sampling using RLPyt  (for 1000 'samples', up to half an hour headless, with all cameras (@128x128)), not our optimization step so much. I'm not passing much in terms of parameters to the RLBench env.

**Comment by stepjam** [comment]
This is now resolved. Please go to PyRep, and simply rerun `pip install .`.
**There is no need to redownload CoppeliaSim 4.1**
