### ISSUE TITLE
It seems get_low_dim_data() method has bug inside

### ISSUE THREAD

**Issue by mch5048** [stepjam/RLBench#16]
Hi, I'm really enjoying this fascinating environment you guys have released to facilitate the RL robotics research.
While I'm implementing some algorithms that is going to be tested on your environment, I encountered an error related to get_low_dim_data() method of Observation() class.
In
 `        low_dim_data = [] if self.gripper_open is None else [self.gripper_open]
        for data in [self.joint_velocities, self.joint_positions,
                     self.joint_forces,
                     self.gripper_pose, self.gripper_joint_positions,
                     self.gripper_touch_forces, self.task_low_dim_state]:
            if data is not None:
                low_dim_data.extend(data)
        return np.concatenate(low_dim_data)`,

the np.concatenate does not work since the gripper_open attribute is float, while others are np.ndarray, resulting the python complaining as

>  return np.concatenate(low_dim_data)
ValueError: zero-dimensional arrays cannot be concatenated 

Is this a minor bug or am I using it in the wrong way?

Thanks in advance!

**Comment by mch5048** [comment]
`low_dim_data = [] if obs.gripper_open is None else [np.array(self.gripper_open).reshape(-1)]
      for data in [self.joint_velocities, self.joint_positions,
                    self.joint_forces,
                    self.gripper_pose, self.gripper_joint_positions,
                    self.gripper_touch_forces, self.task_low_dim_state]:
          if data is not None:
              low_dim_data.append(data)
      for data in low_dim_data:
      return np.concatenate(low_dim_data)`

I changed to code as above and it seems like working fine!

**Comment by stepjam** [comment]
Thanks for pointing out. Fixed in #15.
