### ISSUE TITLE
ModuleNotFoundError: No module named 'rlbench.action_modes'

### ISSUE THREAD

**Issue by Dear-Chen** [stepjam/RLBench#160]
Dear developer,

I installed the package according to the tutorial. Then I tried to run the example(Few-Shot Learning and Meta Learning) in the tutorial. 
When I run 'from rlbench.action_modes.action_mode import MoveArmThenGripper', there were some errors.

ModuleNotFoundError: No module named 'rlbench.action_modes'.

After I checked  the installation path, there was no action_modes submodule there. Then I checked the setup.py file, there was no rlbench.action_modes item in the packages list. So, edit the packages list in the setup.py file could be a solution.

**Comment by dkjung** [comment]
I've just experienced the same problem. Could anyone please answer this issue?

**Comment by Dear-Chen** [comment]
Modify the packages list in the setup.py file as follows.
```python
packages=[
            'rlbench',
            'rlbench.action_modes',
            'rlbench.backend',
            'rlbench.tasks',
            'rlbench.task_ttms',
            'rlbench.robot_ttms',
            'rlbench.sim2real',
            'rlbench.assets',
            'rlbench.gym'
      ]
```
Then install the package again.

**Comment by Dear-Chen** [comment]
> I've just experienced the same problem. Could anyone please answer this issue?

Modify the packages list in the setup.py file as follows.
```python
packages=[
            'rlbench',
            'rlbench.action_modes',
            'rlbench.backend',
            'rlbench.tasks',
            'rlbench.task_ttms',
            'rlbench.robot_ttms',
            'rlbench.sim2real',
            'rlbench.assets',
            'rlbench.gym'
      ]
```
Then install the package again.
`pip install .`
