### ISSUE TITLE
How to obtain Depth Images from the robot

### ISSUE THREAD

**Issue by Zialo** [stepjam/RLBench#164]
Hi everyone!
Before starting, thanks for your awesome work, it's really interesting!
I'm working with RLBench making an Imitation Learning project and I wanna obtain the depth images of the robot. I saw that in the paper we can get this type of image: 
![image](https://user-images.githubusercontent.com/49028287/162960479-65451f8c-a1b5-4bf2-b536-91ec70424fc6.png)
The problem is when the image is made, because I get this other kind of images:
![image](https://user-images.githubusercontent.com/49028287/162960645-53961403-0852-4a62-b426-2ab69b26ee0b.png)

How can I get the depth images like the ones that are shown on the paper?

Thank you again for your time!

**Comment by stepjam** [comment]
Hi,
The saved depth images are encoded. Please load the dataset using the built in data loading (env.get_demo; this will do the depth decoding), and then you can visualise the depth as you see fit (e.g. by accessing `obs.front_depth`).
