### ISSUE TITLE
task.reset() performance question

### ISSUE THREAD

**Issue by Guitaricet** [stepjam/RLBench#17]
Hi! Thank you for RLBench!

I am running `few_shot_rl.py` example (using xvfb) and `task.reset()` takes a full minute to execute. It does not look like the correct behavior to me, so if you could give some advice on what the problem may be (or how to detect it), it would be very nice.

I tried setting OPENGL instead of OPENGL3 in all env cameras, but it did not help.

PC spec:
Ubuntu 18.04
Intel(R) Core(TM) i7-6700K
RAM: 60 Gb
GPUs: GTX 1080 (x2) and Titan V

**Comment by Guitaricet** [comment]
After installing
```bash
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libgl1-mesa-dev
```

It works much faster

**Comment by stepjam** [comment]
You can now do GPU rendering: https://github.com/stepjam/RLBench/blob/master/README.md#running-headless

**Comment by pyun-ram** [comment]
Thank you sooo much! You save my life. :) @Guitaricet 

> After installing
> 
> ```shell
> sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libgl1-mesa-dev
> ```
> 
> It works much faster
