### ISSUE TITLE
Handle Mico_target does not exist

### ISSUE THREAD

**Issue by superggb** [stepjam/RLBench#18]
I just want to replace the Panda arm with Mico arm, I just simply edited the task.ttt where I changed the Panda arm to Mico arm. Then I edited the code: 

    self._robot = Robot(Mico(), MicoGripper())

And when I run the demo script I got the error message.

So is there anybody have success experience to replace the arm ?
Or is there some detailed descriptions for changing arm?

**Comment by stepjam** [comment]
I plan to make it much easier to swap out the arm. Please bear with me on this. Thanks :)
