### ISSUE TITLE
How to read end-effector's velocity out of demos

### ISSUE THREAD

**Issue by Tete-Xiao** [stepjam/RLBench#19]

**Comment by stepjam** [comment]
You can get the end-effector pose from the [observations](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/observation.py) of the demos: e.g. `obs.gripper_pose`. You can then calculate the velocity based on the pose from time `t` and `t-1` and using the simulation timestep amount (which is `50ms` by default).

Happy to accept a pull request if you would like to add this in as a permanent observation in the 
observation.py file.

Best,
Stephen
