### ISSUE TITLE
randomization after reset_to_demo

### ISSUE THREAD

**Issue by TongZhangTHU** [stepjam/RLBench#194]
Hi,

Thank you for your wonderful implementation. 

When I evaluate task 'open_fridge',  I notice that even after calling the [reset_to_demo](https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L164) function, the initial object pose configurations sometimes (although not always) remain different compared to the data. In this situation, I observe that the [init_episode](https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L78) function [attempts](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/scene.py#L126) different numbers of times. I hypothesize that the sampling-based planner used in RLBench introduces a degree of randomization, which leads to different outcomes in the [task validation](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/scene.py#L134) process. Have you made similar observations? If so, do you have any suggestions on how this issue might be resolved?

**Comment by SatireY** [comment]
I have the same problem. Do you have a solution now?

**Comment by zwbx** [comment]
marked as same problem

**Comment by alesspalma** [comment]
@TongZhangTHU have you solved it?
