### ISSUE TITLE
ImportError: No module named 'rlbench.sim2real'

### ISSUE THREAD

**Issue by b0ku1** [stepjam/RLBench#2]
`>>> import rlbench
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File /vrep/lib/python3.5/site-packages/rlbench-1.0-py3.5.egg/rlbench/__init__.py", line 5, in <module>
    from rlbench.sim2real.domain_randomization import RandomizeEvery
ImportError: No module named 'rlbench.sim2real'
`
Hi there, after I install rlbench, the following error occurs. Thanks.

**Comment by b0ku1** [comment]
I can successfully run PyRep examples like : example_baxter_pick_and_pass.py

**Comment by stepjam** [comment]
Thanks for reporting! Yes this was a bug. If you re run the installation of RLBench, this should now work.
