### ISSUE TITLE
How to import a 3D model when building a new task?

### ISSUE THREAD

**Issue by ZJUshine** [stepjam/RLBench#239]
![EA5D7A91-1AF0-4AE4-8419-C720672739D2_1_201_a](https://github.com/stepjam/RLBench/assets/79798486/81bc8c1e-904f-47a3-8056-59b91b3d0bf3)
Dear authors
    I want to build a new task using "task_builder.py", but there is no response while I imported a 3D model (stl or obj format) and click import button. What should I do to fix this bug ?

**Comment by ZJUshine** [comment]
I solve this problem by using pyrep API in task_builder.py

**Comment by rsriram315** [comment]
@ZJUshine What do you mean when you say you used "PyRep API in task_builder.py". Can you please elaborate? I am trying to import an STL file and running into the same issue. Thanks

**Comment by rsriram315** [comment]
@ZJUshine thanks for your reply. My email: rsriram315@gmail.com

**Comment by ZJUshine** [comment]
```
    def import_3d_model(self, model_path):
        print('Importing 3D model from:', model_path)
        if not isfile(model_path):
            print_fail('Model file does not exist!')
            return

        try:
            model = Shape.import_mesh(model_path,scaling_factor=1)
            model.set_parent(self.task.get_base())
            print('3D model imported successfully!')
        except Exception as e:
            print_fail('Failed to import 3D model!')
            traceback.print_exc()
```
This is the main code for importing 3D models, I hope it works for you.

**Comment by rsriram315** [comment]
Thanks for this, I will try this out!
