### ISSUE TITLE
issue while running nvidia-xconfig 

### ISSUE THREAD

**Issue by rebecajohn** [stepjam/RLBench#249]
Command : 

sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024
echo -e 'Section "ServerFlags"\n\tOption "MaxClients" "2048"\nEndSection\n' \
    | sudo tee /etc/X11/xorg.conf.d/99-maxclients.conf

tee: /etc/X11/xorg.conf.d/99-maxclients.conf: No such file or directory
Section "ServerFlags"
        Option "MaxClients" "2048"
EndSection

**Comment by b-karthiknair** [comment]
@rebecajohn  did these commands work for you for headless rendering? When I started the X server with `sudo nohup X :99 & disown`, my screen went black. Even after a reboot, the display remained frozen, and I had to manually revert `/etc/X11/xorg.conf` to make it functional again. Did you encounter similar issues or find a workaround?
