### ISSUE TITLE
Tasks with button presses never complete successfully

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#28]
I have tried collecting demos in the TvOn, TvOff, and ChangeChannel tasks, as well as PushButton and PushButtons, but none of them complete successfully. They all get initialized correctly and the robot plans and executes the motions, but it seems the actual button presses are maybe not being registered? The environment just keeps resetting and executing the task without success.

**Comment by stepjam** [comment]
Thanks for reporting. Will take a look at this later today.

**Comment by adamconkey** [comment]
I was able to run all of the tasks except LampOn, that one still seems to not respond to a button press.

**Comment by stepjam** [comment]
Thanks. This is now resolved :smile:.
