### ISSUE TITLE
Segmentation mask for wrist camera not tracking with RGB/Depth

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#30]
The segmentation mask for the wrist camera seems to stay where it was initialized, instead of tracking with the movement of the hand. This can be seen in the GIF below that shows the wrist RGB and wrist segmentation mask side-by-side synchronized in time. I'll emphasize that the segmentation mask is **not** from one of the shoulder cams, it actually is associated with the wrist camera.

![Peek 2020-01-11 12-43](https://user-images.githubusercontent.com/22223086/72209836-321d8b80-3470-11ea-9448-419a0077d388.gif)

**Comment by stepjam** [comment]
Hi Adam,
Thanks for pointing out. I can resolve this later today :)
