### ISSUE TITLE
Add videos of each task

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#32]
This is a feature request. I think it would be nice to have a way of viewing an execution of each task without actually having to load up the simulator and run it. Your YouTube video that gives an overview of RLBench is very nice, but I'm still finding that I see a task name and, though it's descriptive, I ideally could watch a video of it so I know exactly what the robot is going to try to do. 

If this is impractical then you can close, but a couple thoughts are having a readme page with GIFs that show each task, or having YouTube videos of each task that you can just click to and watch the video.

My current use case is I've recorded demos for every task in a headless manner. I'm now trying to divide the data into train/test sets so I know if they were seen/unseen environments in testing, but it's hard for me to tell without actually launching the simulator or trying to see if it's shown in your overview YouTube video.

**Comment by stepjam** [comment]
Yes, I think this is a good idea. hopefully will update this issue in a few days :smile:.

**Comment by adamconkey** [comment]
I made some GIFs of each task for my own purposes, figured I could share them with you. Has RGB feed for each task from all three camera views, I left it in a flat structure so you can just click through them one by one and see them right in Google Drive: https://drive.google.com/drive/folders/1TqbulbbCEqVBd6SBHatphFlUK2JQLkYu?usp=sharing

**Comment by stepjam** [comment]
Ohh, that's very helpful. Thanks!
Apologies for not getting around to doing it myself yet; have been prioritising bugs. I can add a link to this in the readme :)

**Comment by eugeneteoh** [comment]
@adamconkey do you happen to still have the GIFs? The gdrive link has expired.

**Comment by DingChunQ** [comment]
Is there a way to view these GIFs now?
