### ISSUE TITLE
Example RL algorithms or other repos utilizing RLBench?

### ISSUE THREAD

**Issue by ahundt** [stepjam/RLBench#33]
So you’re saying there is no other RL repository which already has this one integrated? Correct me if I’m mistaken, but if there are no known, working, and integrated clients I feel like there will be a lot of debugging to do in this project and it may not be ready for use unless one is willing to go through debugging the whole API themselves. I'm not trying to criticize, rather I’m asking to understand the scope of work if I were to use this project seriously. I have a paper & project which uses the vrep api and I’m figuring out the possibility of integrating that with this work https://github.com/jhu-lcsr/good_robot.

Sorry for duplicating https://github.com/stepjam/RLBench/issues/25, but my followup question seems to have been lost, and I can't figure out how to reopen it.

**Comment by stepjam** [comment]
I'm not sure what you mean by a repository that 'integrates' this one. RLBench is an environment, and so it can be used with any reinforcement learning repository. The repo is well tested both through unit tests, task integration tests, and manual use through myself and others who use this project; of course bugs will emerge over time, but we are continuing to improve.

**Comment by ahundt** [comment]
Do you know of any public pytorch code which already supports RLBench?

I can see [RLzoo](https://github.com/tensorlayer/RLzoo/blob/ea5a5734e7a9a9d9610b7405ec1954302cb80c83/rlzoo/common/build_rlbench_env.py), which you suggested, does have integrated support, but it uses TF.

**Comment by stepjam** [comment]
Hi,
Not that I am aware of, but any framework that 'supports' OpenAI Gym will automatically be compatible with RLBench.
