### ISSUE TITLE
please add examples

### ISSUE THREAD

**Issue by bionicles** [stepjam/RLBench#4]
Would it be possible to add a full working example with tf2.0 keras? The current examples seem to only have numpy random actions

**Comment by stepjam** [comment]
Hi. The examples are meant to be as lightweight as possible. I feel like having the examples littered with machine learning framework code would be a distraction to the core RLBench things I'm trying to show.
Nonetheless, I'm happy to take pull requests for tf2.0 examples in a new '_tf_examples_' folder if anyone is interested :)
