### ISSUE TITLE
Manually setting poses of objects in scene to recreate previously used scenes

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#41]
There is probably a simple way to do this but I've been digging through source for a while and don't yet see it. Instead of randomly initializing a scene, I would like to place the objects in the scene at set poses in the workspace. My use case is I want to record demos where objects in the scene are placed randomly in the workspace, and then later I want to be able to recreate those same scene configurations. Is there a simple way to do this with the existing infrastructure?

**Comment by stepjam** [comment]
Hi Adam,
Not in the existing infrastructure, but it's easy to add in. However, I was planning to make 'reset to demo' a bit more general, where you can specify any point along the demonstration to reset to; this is a little more tricky.
Anyway, I can roll this in to V1.0.5, which I hope to push out in the next day or two.

**Comment by adamconkey** [comment]
Hi Stephen,
That would be really helpful to me. Right now I just need to take whatever initial configuration was set for a previously recorded demo, and make that the current configuration.
Thanks!
