### ISSUE TITLE
Why does segmentation mask have 3 channels?

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#43]
The segmentation masks all have 3 channels, but only the first channel contains meaningful numbers and the other 2 channels are all zeros. Is there a reason behind this?

**Comment by stepjam** [comment]
Hi Adam,
This is how CoppeliaSim returns segmentation masks. It first fills the R channel (until 255), then G, then B. I think they do it this way to make it easier to visualise the masks; however, maybe for RLBench we should convert it to a one channel standard. Would you prefer that?

**Comment by adamconkey** [comment]
Hi Stephen, one argument for making it single channel is it cuts down on storage space. I'm storing all my data in HDF5 files and loading the files can take longer the larger the file size. Also I spent a while thinking about why there would be 3 channels until I realized only one channel actually had data in it, so maybe from an interpretability standpoint it would also be helpful.
