### ISSUE TITLE
[Feature Request / Help] rgb_array rendering for gym

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#46]
New to the library — right now, gym.render only supports 'human', so it opens a window for the camera. Would it be possible to get the rgb_array for the scope camera just like for the wrist/shoulders, and return that from env.render("rgb_array", width, height)?

**Comment by bycn** [comment]
Could set up a camera with task builder and invoking that camera

**Comment by stepjam** [comment]
Sure, I'll add this in to V1.0.6.
