### ISSUE TITLE
Imitation learning prediction - Question

### ISSUE THREAD

**Issue by raghada** [stepjam/RLBench#49]
For the imitation learning example script, is it possible to send the predicted actions to the scene instead of just computing the loss?

By this I mean, can I test the robot with my networks' prediction?

I basically know how to do this with PyRep, but not with RLBench. Would really appreciate it if you can advise.

Thanks for the great work and effort you are putting on this!

**Comment by stepjam** [comment]
Something like this?
https://github.com/stepjam/RLBench/blob/master/examples/single_task_rl.py

**Comment by raghada** [comment]
Yes, very much appreciated :)
