### ISSUE TITLE
Why does the arm move sometimes slowly somtimes fast?

### ISSUE THREAD

**Issue by HeegerGao** [stepjam/RLBench#51]
Hi, I am using jaco for reinforcement in RLBench. I tried the RLBench/examples/single_task_rl.py and I have two questions:

1. How to set jaco arm correctly? 
At first, I just set like this:
`env = Environment(action_mode=action_mode, robot_configuration='jaco', obs_config=obs_config, headless=False)`
But it comes out an error:
```
Traceback (most recent call last):
  File "rlbench_test.py", line 44, in <module>
    obs, reward, terminate = task.step(action)
  File "/home/gck/.local/lib/python3.6/site-packages/rlbench/task_environment.py", line 147, in step
    (len(self._robot.arm.joints),))
  File "/home/gck/.local/lib/python3.6/site-packages/rlbench/task_environment.py", line 109, in _assert_action_space
    str(expected_shape), str(np.shape(action))))
RuntimeError: Expected the action shape to be: (6,), but was shape: (7,)
QObject::~QObject: Timers cannot be stopped from another thread
QMutex: destroying locked mutex
```
I think this is because the action number is not set correctly, so I go to your code (action_modes.py) and find how to set it. Then I add two lines and it runs normal:
```
action_mode.arm.action_size = 6
action_mode.action_size = action_mode.arm.action_size + action_mode.gripper.action_size
```
I don't know if this is a proper way, so I want to ask you for suggestion.

2. Why does the arm move sometimes slowly somtimes fast?
When I run the RLBench/examples/single_task_rl.py, I find the time of every loop is quite difference:
```
for i in range(training_steps):
    if i % episode_length == 0:
        print('Reset Episode')
        descriptions, obs = task.reset()
        print(descriptions)
    action = agent.act(obs)
    print(action)
    obs, reward, terminate = task.step(action)
    print('steps:',i)
```
In the simulation, one 'step' function sometimes lasts for 1s or 2s sometimes only for 1ms. It looks like [this](https://cloud.tsinghua.edu.cn/f/8e8890a49bc748eaa3e8/). You can see that it seems like sometimes the step function just stucks.

**Comment by stepjam** [comment]
I am looking into this
