### ISSUE TITLE
Success returns the same value for both reward and done

### ISSUE THREAD

**Issue by raghada** [stepjam/RLBench#57]
https://github.com/stepjam/RLBench/blob/8ff9507a7b6be5b374f6b7e619b4b7eda1f9fd57/rlbench/backend/task.py#L261

Am I missing something?

**Comment by bycn** [comment]
sparse reward, so rew = 1 = done = True, rew = 0 = done = False

**Comment by stepjam** [comment]
Hi both. What @bycn is not quite right; what he said is true on the environment level (calling `env.step`). However, that particular success function was originally going to return both success value and if any constraints were breached, but I decided not to include it, hence why it returns the same value for both. I will refactor this out in future. 

I wouldn't worry too much about it as its a backend function and you shouldn't need to use it.
