### ISSUE TITLE
slide_block_to_target rendered incorrectly in camera views

### ISSUE THREAD

**Issue by nimaasg** [stepjam/RLBench#59]
For **slide_block_to_target** task, the object and target are not rendered correctly in cameras (see attached screenshots. I haven't seen this issue in any other task.

![Screenshot_2020-04-15_17-32-09](https://user-images.githubusercontent.com/1252912/79402308-4de96f80-7f40-11ea-949b-c576efa81a95.png)
![67](https://user-images.githubusercontent.com/1252912/79402335-66f22080-7f40-11ea-9813-175b947be8f2.png)

**Comment by stepjam** [comment]
This is now resolved in branch 1.0.7, which will be merged to main soon :)
Thanks for reporting.
