### ISSUE TITLE
How did you record those nice videos?

### ISSUE THREAD

**Issue by ascane** [stepjam/RLBench#6]
This is just a question, not an issue.

Could you please share how you recorded your videos? I used the video recorder in V-REP, but the videos contain all the red or blue lines in simulation. Did you add a camera (with high resolution) and make it rotate programmtically? If so, could you please share that code?

**Comment by ascane** [comment]
Great, thank you! Looking forward to it.

**Comment by adamconkey** [comment]
Has this been added yet? I am interested in getting higher resolution videos and am having a hard time figuring out these cameras in CoppeliaSim.

**Comment by stepjam** [comment]
Sorry @ascane , this got buried in my todo list. @adamconkey: I'll get this added in today.

**Comment by adamconkey** [comment]
Awesome, thanks!
