### ISSUE TITLE
Gifs are buggy?

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#63]
https://drive.google.com/drive/folders/1TqbulbbCEqVBd6SBHatphFlUK2JQLkYu

Ex., the block to target tasks look like they are grabbing nothing to the goal

**Comment by bycn** [comment]
never mind, the cameras just don't see the block. Weird, since i'd assume this should be necessary for the task to be completed.

**Comment by stepjam** [comment]
Hi,
No you were originally right... the block was previously not rendered, but this was fixed a while ago. The gifs were made before the bug fix.

**Comment by bycn** [comment]
Would it be possible to link the commits for the fix?

**Comment by bycn** [comment]
Found it @59
