### ISSUE TITLE
How to serialize FFI CData to disk to restore state?

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#65]
I am hoping to use the `get_state` and `restore_state` functions on the tasks to re-initialize an environment exactly as it was in a recorded demo. This does work, but my problem is I want to save the state to disk (I don't care what format) and be able to reload it later to restore the state. It looks something like `(<cdata 'char *' 0x55c54298da10>, 5)`, and it's this cdata type that is causing trouble no matter how I try to (de)serialize it. I tried pickle, dill, writing and loading just as binary. I have been trying for hours and am quite stuck. Do you know of a way to handle this?

**Comment by bycn** [comment]
Have you tried writing the bytes to a binary file? i.e., open('filename', 'wb').write(bytes_)

**Comment by bycn** [comment]
https://cffi.readthedocs.io/en/latest/ref.html#ffi-cdata-ffi-ctype
You need to call ffi.string(cdata) and then just write the bytes as binary

**Comment by adamconkey** [comment]
I had tried that, writing to bytes I could do, it's loading them back into cdata that `restore_state` can use that was the challenge and I had no success with that part. I tried various things with reading the bytes into buffers but just couldn't get it to work.

**Comment by stepjam** [comment]
Hi,
This functionality already exists:
``````

**Comment by adamconkey** [comment]
Thanks Stephen, I think this works for me.

**Comment by bycn** [comment]
@adamconkey did you ever get this to work or did you just use stephen's "solution"? I'm trying to do multiprocessing and the cdata has to be serialized (i.e., i have to send the bytes instead), but loading it back in gives some segmentation fault errors.
