### ISSUE TITLE
Success sensor with block?

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#66]
I have a block and a success sensor. It registers a sucess when the block.get_position() - sensor.get_position() is nonzero, and not only this, but when it is closer it does not register success (so it can't be an epsilon ball). When viewing images, it seems like it takes one of the corners of the block as the position. What's the right way to do this so it senses the middle of the block?

**Comment by stepjam** [comment]
Hi,
Maybe I am misunderstanding, but why not just make the proximity sensor smaller?

**Comment by stepjam** [comment]
Yes, calling get_position on a pyrep object will give you the position of the objects centre.
When you say you have a 'success sensor', what do you mean? Do you mean a [proximity sensor](https://github.com/stepjam/PyRep/blob/master/pyrep/objects/proximity_sensor.py) or [condition](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/conditions.py)?

**Comment by bycn** [comment]
Proximity sensor. It seems not to use the position() to calculate success

**Comment by stepjam** [comment]
No it doesn't use get_position. You can if you want define your own Condition that calculates an explicit distance within some delta (using get_position), however I would suggest using the [proximity condition](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/conditions.py#L43) as this is much nicer to visualise when defining your task. You can make your proximity sensor as small or as big as you like to get the same effect as a get_position approach would give you :)

**Comment by stepjam** [comment]
Please reopen if you still need help with this :)
