### ISSUE TITLE
Using segmentation mask

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#69]
Hi,

I'm trying to create a camera in the scene and then get the segmentation mask from it. How would I do this? 

Context for my specific use case: This is after env.launch() is called, I do      
`   self.cam = VisionSensor.create([img_size, img_size])
`
and it works, but how do I get the mask from this? For the cameras given in the scene there exists corresponding mask cams,  i.e., for cameraovershoulderleft there is cameraovershouldlerft_mask, but i check the ttm and there isn't any cameraovershoulder_mask in the scene.

looking at this commit https://github.com/stepjam/RLBench/commit/d0006faeb195b52a6c19306222c05d7cc40f35b9
maybe the mask cams are done manually? How can I dynamically make a cam have a corresponding mask one?

**Comment by bycn** [comment]
Found it

**Comment by Zhangwenyao1** [comment]
> Found it
Thanks for your great comments . Can you tell me how to solve this problem?
