### ISSUE TITLE
May I ask why the robot arm can only move a little when I run single_task_rl.py

### ISSUE THREAD

**Issue by ZZ-111** [stepjam/RLBench#70]
First of all thank you for building this great project.
when I run single_task_rl.py the robot arm can only move a little .
![recording_2020_06_03-01_20-23](https://user-images.githubusercontent.com/55341540/83550372-55d59100-a539-11ea-8cf3-5aff634b92d3.gif)
What code do I need to modify to make the robot arm [move like this.](https://cloud.tsinghua.edu.cn/f/8e8890a49bc748eaa3e8/)
Looking forward to your reply.

**Comment by stepjam** [comment]
In that example, the action mode is joint velocities, and the actions are sampled from a normal. This makes the robot end-effector stay somewhat in the same location. You could multiply this action by some constant to increase the random velocities.
