### ISSUE TITLE
Fixed pose for demos? 

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#71]
Hi,

For my use case I would like the demos to be able to work with a fixed pose (i.e., gripper remains upright the entire time), how would I go about doing this?  Thank you!

As an aside, could you possibly explain what "gripper touch forces" are? My understanding is they are a measure of the force and not part of the input.. But my main question is, how can I recreate an end effector action based on the demo? I guess as soon as the delta in gripper.get_open_amount() after a step is positive, we start a gripper open/close action correspondingly?

**Comment by stepjam** [comment]
Hi,
For the first point, I don't see how this will be possible for the majority of the tasks as they will not be solvable if you restrict the rotation of the gripper, and so it would not be possible to even get demos. 
For the second point; yes the gripper forces are an optional observation you can request. The only way to control the end-effector currently is the last value in the action vector (which should be between 0 and 1). If < 0.5 then it will close until it cannot close anymore, and if > 0.5 it will try and fully open.
Best,
Stephen

**Comment by bycn** [comment]
Hi James,
Thanks for the response. 
For the first point, let's say I create a custom task that is solvable with the pose fixed. How would I go about getting demos with fixed pose?
