### ISSUE TITLE
Segmentation Mask Labels

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#72]
Is there a way to recover the actual name of the class from the segmentation mask? In the case that an object is occluded completely in the scene, there's no way to identify the labels anymore.

**Comment by stepjam** [comment]
You can get the CoppeliaSim object handles. With that, you can access the object if you wish, and then consequently access the 'name' of that object. For example: 
```python
# Here we tell rlbench to return the mask on the form of object handles 
# (rather than a tytpical segmentation mask)
observation_config.left_shoulder_cam.masks_as_one_channel = False
# ... now give the config to rlbench ...
# ... get observation ...
object_handle = left_shoulder_mask.mymask[0, 0]  # Get top right handle

from pyrep.objects.object import Object
object_name = Object.get_object_name(object_handle)
```
