### ISSUE TITLE
A potential bug ?

### ISSUE THREAD

**Issue by imankgoyal** [stepjam/RLBench#82]
Hello, 

Is there a bug in this line (https://github.com/stepjam/RLBench/blob/master/rlbench/backend/task.py#L268)? The function seems to be returning success as both elements in the tuple. As far as I understand, the second element should be related to termination as expected here (https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L289).

Also, are these lines unnecessary (https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L88-L89)?

Best, Ankit

**Comment by stepjam** [comment]
Hi. Thanks for pointing out :)
Not a bug; this was just a feature that I did not end up using (the second value in the tuple is never used anywhere). I plan to remove it in a refactor sweep at some point, but this wont change the behaviour of how success operates.

> Also, are these lines unnecessary (https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L88-L89)?

It seems like they aren't necessary. Will take these out in the 1.0.9 release. I'll leave this open until I do these refactors.
