### ISSUE TITLE
Import Ur5 Manipulator

### ISSUE THREAD

**Issue by kamaleshrathinam** [stepjam/RLBench#86]
How can I use ur5 arm in Rlbench?

**Comment by stepjam** [comment]
Please see this: https://github.com/stepjam/RLBench/tree/1.0.8#swapping-arms
Ur5 is in PyRep, and so we can bring this into RLBench. I should have time to get this done today or tomorrow.

**Comment by kamaleshrathinam** [comment]
Awesome, Thank You
