### ISSUE TITLE
Using robotic arms other than "panda" will report errors

### ISSUE THREAD

**Issue by fanSunny** [stepjam/RLBench#87]
When creating an environment, read robot_configuration ='jaco' or'mico' or'sawyer' and an error will be reported: rlbench.task_environment.TaskEnvironmentError: Could not place the task reach_target in the scene. This should not happen, please raise an issues on this task .And Coppeliasim reported an error:[simExtIK:error]Found invalid joint handle(s).

**Comment by stepjam** [comment]
Hi. What task do you get this error with?

**Comment by fanSunny** [comment]
> Hi. What task do you get this error with?
Many tasks went wrong, such as ReachTarget.
An error was reported when calling ‘python imitation_learning.py’, I only changed the parameters:
env = Environment(action_mode,DATASET,obs_config,False,**robot_configuration='jaco'**).
thanks~

**Comment by tunglm2203** [comment]
Hi @fanSunny , I have the same problem with you, have you try successfully in 'sawyer'?

**Comment by fanSunny** [comment]
> Hi @fanSunny , I have the same problem with you, have you try successfully in 'sawyer'?

Hi@tunglm2203,I tried using ‘sawyer’ but it was still unsuccessful.

**Comment by stepjam** [comment]
I assume this is related to #94 .
Fix will be here by end of week
