### ISSUE TITLE
Could not initialize GLX - in headless mode

### ISSUE THREAD

**Issue by dhruvramani** [stepjam/RLBench#89]
I am trying to run RLBench on a headless server. I set the `headless` flag as `True` while creating an `Environment`. But whenever I do `task.reset()`, the script crashes with the following error :

```shell
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 3.2, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize 0, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 3.2, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize 0, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
Could not initialize GLX
Aborted (core dumped)
```
I ran the examples in PyRep repo and that worked perfectly fine.
Can anyone help me with this? Thanks a lot!

**Comment by dhruvramani** [comment]
I suppose this has something to do with the `VisionSensor` used in `get_observation()` in `scene.py`. I am guessing that I can't work with RGB(D) images if I am using a headless server then?

**Comment by stepjam** [comment]
Did you follow the headless instruction in PyRep? https://github.com/stepjam/PyRep#running-headless

**Comment by dhruvramani** [comment]
Yes, I did that. I think the problem is coming up while calling [`sensor.handle_explicitly()` in `scene.py`](https://github.com/stepjam/RLBench/blob/20988254b773aae433146fff3624d8bcb9ed7330/rlbench/backend/scene.py#L186). 
`sensor.capture_rgb()` works fine.

**Comment by dhruvramani** [comment]
I was looking at your comment [here](https://github.com/stepjam/PyRep/pull/43#issuecomment-565983234), and I think you're calling `sensor.capture_rgb()` without calling `sensor.handle_explicitly()`. Is it okay to comment this out in `scene.py`? 
`sensor.capture_rgb()` wasn't raising any errors.

**Comment by stepjam** [comment]
Theres no error raised with you because `sensor.capture_rgb()` doesn't actually render anything, it returns an already rendered image, which will be blank unless you call `sensor.handle_explicitly()`. There must be an issue with _how_ you are running the program.
Could you tell me exactly the command you are running when launching rlbench?

**Comment by stepjam** [comment]
> Is it possible to use `VisionSensor` if using a headless server?

Yes, just to be clear, RLBench runs fine headlessly.

**Comment by dhruvramani** [comment]
> Could you tell me exactly the command you are running when launching rlbench?

I was just trying this on the examples in the repo to fix this right now. I am running the program like this : 
```shell
xvfb-run -a python3 single_task_rl.py
```

**Comment by stepjam** [comment]
OK. Perhaps try launching this way instead:
```
Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset &
export DISPLAY=:99
python3 single_task_rl.py
```

**Comment by dhruvramani** [comment]
Thanks a lot that worked! Can you tell me what's happening in the first comment?

**Comment by stepjam** [comment]
I think `xvfb-run -a python3 single_task_rl.py` doesn't work because only the python interpreter gets access to the display, and not the CoppeliaSim process that spawns off from that. Whereas the other solution creates a permanent display (line 1) and then everything  from that point (after calling `export DISPLAY=:99`) uses this new display.

**Comment by dhruvramani** [comment]
Ohh okay. That's interesting, didn't think of that. Thanks a lot! Amazing work with this :)

**Comment by tunglm2203** [comment]
Hi @dhruvramani, I have the same problem with, I have tried to launch like this:

> OK. Perhaps try launching this way instead:
> 
> ```
> Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset &
> export DISPLAY=:99
> python3 single_task_rl.py
> ```

But I have another problem: 

`/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libcoppeliaSim.so.1(_Z11_segHandleri+0x28)[0x7fbd5c5c70b8]
/lib/x86_64-linux-gnu/libc.so.6(+0x354c0)[0x7fbdc31344c0]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libQt5Gui.so.5(_ZNK14QOpenGLContext10shareGroupEv+0x0)[0x7fbd5aed7060]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libQt5Gui.so.5(_ZN16QOpenGLFunctions25initializeOpenGLFunctionsEv+0x4b)[0x7fbd5b1a3a4b]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libQt5Gui.so.5(_ZN24QOpenGLFramebufferObjectC1EiiNS_10AttachmentEjj+0xc8)[0x7fbd5b1a7a18]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libsimExtOpenGL3Renderer.so(_ZN18CFrameBufferObjectC2Eii+0x54)[0x7fbd2d8753b4]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libsimExtOpenGL3Renderer.so(_ZN16COpenglOffscreenC1EiiiP14QOpenGLContext+0x68)[0x7fbd2d875758]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libsimExtOpenGL3Renderer.so(_Z21executeRenderCommandsbiPv+0x1f59)[0x7fbd2d873bd9]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libcoppeliaSim.so.1(_ZN16CPluginContainer11extRendererEiPv+0x15)[0x7fbd5c772065]
/mnt/hdd/tung/workspace/rlbench/CoppeliaSim/libcoppeliaSim.so.1(_ZN13CVisionSensor24_extRenderer_prepareViewEi+0x34f)[0x7fbd5c4a2e1f]
QMutex: destroying locked mutex`.

Did you have the same problem as this?

System information:
Running script: `python3 single_task_rl.py`
Python version: 3.7.9 (anaconda)
RLBench: 1.0.8
PyRep: 1.2

**Comment by stepjam** [comment]
You can now do GPU rendering: https://github.com/stepjam/RLBench/blob/master/README.md#running-headless
