### ISSUE TITLE
[Bug]Creating Scene via Task Builder 

### ISSUE THREAD

**Issue by mertimre** [stepjam/RLBench#9]
Hi, 
I installed PyRep and RLBenchmark. They together seem promising. I have encountered two bugs while following the "Simple Task Walkthrough". 

1)
When trying to run the task builder, it was not able to find the task validator. So I needed to change the import at the start of task builder 
from
from tools.task_validator import task_smoke, TaskValidationError
to 
from task_validator import task_smoke, TaskValidationError

2) 
While trying to create a non-existing task, at first it says that it does not exist in the system, would you like to create it. However, when you want to create it the system throws errors as follows: (XXXX is the new task name)
ModuleNotFoundError: No module named 'rlbench.tasks.XXXX'
rlbench.utils.InvalidTaskName: The task file 'XXXX' does not exist or cannot be compiled.

And a small note, the task in the tutorial slide_block_to_target already exists, you may want to change it as in the screenshot to slide_block

Best

**Comment by superggb** [comment]
I found the second BUG too.
But I still haven't found solution.
Do u solved this?

**Comment by bycn** [comment]
Ran into similar but reinstall & re-setup fixed it
