### ISSUE TITLE
would it possible for more realistic grasping as in real world

### ISSUE THREAD

**Issue by v-wewei** [stepjam/RLBench#97]
dear author, 
would it possible for more realistic grasping as in the real world, since rlbench give fake grasping by proximity sensor in the middle of the gripper tips.  

Thanks,

**Comment by stepjam** [comment]
I can certainly provide a function that would allow you to turn off the fake grasping. Would this be OK?
Bare in mind that some of the tasks' demos will most likely fail in this mode though.

**Comment by v-wewei** [comment]
@stepjam yes, I would like to avoid the fake grasping in our env.  Thanks very much! 
So, where can I found the function?

**Comment by stepjam** [comment]
This is now in 1.0.9 (which will soon be merged to main). You can disable the fake grasping by:

```
e = Environment(..., attach_grasped_objects=False)
```
